<?php

namespace ContainerIGjSJWS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DmUbEwaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dmUbEwa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dmUbEwa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'incidenciaRepository' => ['privates', 'App\\Repository\\IncidenciaRepository', 'getIncidenciaRepositoryService', true],
        ], [
            'incidenciaRepository' => 'App\\Repository\\IncidenciaRepository',
        ]);
    }
}
