<?php

namespace ContainerIGjSJWS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FNKjjcXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fNKjjcX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fNKjjcX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'controlRepository' => ['privates', 'App\\Repository\\ControlRepository', 'getControlRepositoryService', true],
        ], [
            'controlRepository' => 'App\\Repository\\ControlRepository',
        ]);
    }
}
