<?php

namespace ContainerXNxWl2N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AjeKrodService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AjeKrod' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AjeKrod'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'empleadosRepository' => ['privates', 'App\\Repository\\EmpleadosRepository', 'getEmpleadosRepositoryService', true],
        ], [
            'empleadosRepository' => 'App\\Repository\\EmpleadosRepository',
        ]);
    }
}
