<?php

namespace ContainerXNxWl2N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LzgqbUEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lzgqbUE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lzgqbUE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coch' => ['privates', '.errored..service_locator.lzgqbUE.App\\Entity\\Coches', NULL, 'Cannot autowire service ".service_locator.lzgqbUE": it references class "App\\Entity\\Coches" but no such service exists.'],
        ], [
            'coch' => 'App\\Entity\\Coches',
        ]);
    }
}
