<?php

namespace Container6mGQxyV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zcqh8XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zcqh8_X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zcqh8_X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'incidencia' => ['privates', '.errored..service_locator.Zcqh8_X.App\\Entity\\Incidencias', NULL, 'Cannot autowire service ".service_locator.Zcqh8_X": it references class "App\\Entity\\Incidencias" but no such service exists.'],
        ], [
            'incidencia' => 'App\\Entity\\Incidencias',
        ]);
    }
}
