<?php

namespace Container6mGQxyV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIncidencias2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ny2_v8K.App\Entity\Incidencias' shared service.
     *
     * @return \App\Entity\Incidencias
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ny2_v8K": it references class "App\\Entity\\Incidencias" but no such service exists.');
    }
}
