<?php

namespace Container6mGQxyV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIncidenciasTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\IncidenciasType' shared autowired service.
     *
     * @return \App\Form\IncidenciasType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/IncidenciasType.php';

        return $container->privates['App\\Form\\IncidenciasType'] = new \App\Form\IncidenciasType();
    }
}
