<?php

namespace ContainerA12jKT5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Aze_ASService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Aze_.AS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Aze_.AS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'incidenciasRepository' => ['privates', 'App\\Repository\\IncidenciasRepository', 'getIncidenciasRepositoryService', true],
        ], [
            'incidenciasRepository' => 'App\\Repository\\IncidenciasRepository',
        ]);
    }
}
