<?php

namespace ContainerGs9ddjF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_57wEZHhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.57wEZHh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.57wEZHh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'control' => ['privates', '.errored..service_locator.57wEZHh.App\\Entity\\Control', NULL, 'Cannot autowire service ".service_locator.57wEZHh": it references class "App\\Entity\\Control" but no such service exists.'],
        ], [
            'control' => 'App\\Entity\\Control',
        ]);
    }
}
