<?php

namespace Container4FeMNMc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getControlTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ControlType' shared autowired service.
     *
     * @return \App\Form\ControlType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ControlType.php';

        return $container->privates['App\\Form\\ControlType'] = new \App\Form\ControlType();
    }
}
