<?php

namespace Container863Dfny;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6ziujwoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6ziujwo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6ziujwo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'incidencium' => ['privates', '.errored..service_locator.6ziujwo.App\\Entity\\Incidencia', NULL, 'Cannot autowire service ".service_locator.6ziujwo": it references class "App\\Entity\\Incidencia" but no such service exists.'],
        ], [
            'incidencium' => 'App\\Entity\\Incidencia',
        ]);
    }
}
