<?php

namespace Container863Dfny;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JxG0mUzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JxG0mUz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JxG0mUz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coch' => ['privates', '.errored..service_locator.JxG0mUz.App\\Entity\\Coches', NULL, 'Cannot autowire service ".service_locator.JxG0mUz": it references class "App\\Entity\\Coches" but no such service exists.'],
            'cochesRepository' => ['privates', 'App\\Repository\\CochesRepository', 'getCochesRepositoryService', true],
        ], [
            'coch' => 'App\\Entity\\Coches',
            'cochesRepository' => 'App\\Repository\\CochesRepository',
        ]);
    }
}
