<?php

namespace Container863Dfny;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIncidenciaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6ziujwo.App\Entity\Incidencia' shared service.
     *
     * @return \App\Entity\Incidencia
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6ziujwo": it references class "App\\Entity\\Incidencia" but no such service exists.');
    }
}
