<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEzZyBAe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEzZyBAe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEzZyBAe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEzZyBAe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEzZyBAe\App_KernelDevDebugContainer([
    'container.build_hash' => 'EzZyBAe',
    'container.build_id' => 'ad1cc3a1',
    'container.build_time' => 1654545534,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEzZyBAe');
