<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2dN0qS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2dN0qS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX2dN0qS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX2dN0qS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX2dN0qS\App_KernelDevDebugContainer([
    'container.build_hash' => 'X2dN0qS',
    'container.build_id' => '2abcc014',
    'container.build_time' => 1654546846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2dN0qS');
