<?php

namespace ContainerX2dN0qS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getControl2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.57wEZHh.App\Entity\Control' shared service.
     *
     * @return \App\Entity\Control
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.57wEZHh": it references class "App\\Entity\\Control" but no such service exists.');
    }
}
